# Generated by Django 4.2.6 on 2024-10-12 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_service"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Service",
            new_name="Category",
        ),
    ]
